### ISSUE TITLE
掉线后如何不需要重新绑定频道进行登录？

### ISSUE THREAD

**Issue by silsuer** [lzyyauto/efb2w#6]
请问掉线之后如何重新登录？我使用efb2w，容器关闭后重新开启，docker logs -f 容器id后，扫描二维码显示登录成功，但是没有任何反应，电脑版微信也没有被挤掉，也无法接受消息，只能重新启动一个新的容器，但是这样的话，之前绑定的公众号就会丢失掉。需要重新手动绑定，很麻烦

**Comment by lzyyauto** [comment]
好久没维护了居然还有人在用,不重新绑定是不可能的.因为这个本质上是网页版微信转发.

**Comment by lzyyauto** [comment]
网页版微信的wx_id是每次登陆的时候产生的.这个跟每一次都不一样.所以没法保持
